@startuml SoundBond
!include ./commons.style


class Sound {
    +url : string
    +size : int 
    +codec : string
    +startTime : int
    +stopTime : int
    +duration : int
}


class SoundLocation {
    +longitude : float
    +latitude : float
}


class User {
    +first_name : string
    +last_name : string
    +email : string
    +password : string

    +like();
    +follow();
    +comment();
}

class Post  {
    +description : string
    +pub_date : Date

    +getLikes();
    +getComments();
}

User -- Post
Post -- Sound
Sound -- SoundLocation

@enduml